services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_db_net

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      JWT_KEY: ${JWT_KEY}
      PROD_DB_USERNAME: ${PROD_DB_USERNAME}
      PROD_DB_PASSWORD: ${PROD_DB_PASSWORD}
      PROD_DB_NAME: ${PROD_DB_NAME}
      PROD_DB_HOSTNAME: ${PROD_DB_HOSTNAME}
      PROD_DB_DIALECT: ${PROD_DB_DIALECT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_db_net
      - application_net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - application_net

volumes:
  postgres_data:

networks:
  backend_db_net:
    driver: bridge
  application_net:
    driver: bridge

